version: "3.8"

services:
  user-service:
    build: .
    image: user-service:latest
    container_name: user_service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL:-postgres://postgres:postgres@db:5432/mydb?sslmode=disable}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user_service_network

  db:
    image: postgres:17-alpine
    restart: always
    container_name: user_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mydb}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_service_network

volumes:
  postgres_data:

networks:
  user_service_network:
    name: user_service_network
    driver: bridge